- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update respositories
      apt:
        update_cache: yes
      changed_when: False
  
  tasks:
    - include: tasks/packages.yml